---
title: "Introducing Kasa AI"
description: |
  Accelerating innovation in insurance analytics through open collaboration.
author:
  - name: Kevin Kuo
    affiliation: RStudio
date: 04-01-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


Kasa AI is a not-for-profit community-driven initiative for insurance analytics research. Our goal is to improve workflows and advance applied artificial intelligence in the insurance industry through open collaboration. 

### Background

Insurance, by and large, has a reputation of being slow to innovate. Whether this view is warranted or not, we can appreciate the contrast with the tech community, which has brought big data and AI into the mainstream in recent years. The culture of collaboration through open source projects and open access to research has often been credited for these technological advances. We believe that we can effect similar progress in insurance by moving towards a model of open collaboration. 

We outline below some aspects of today’s workflows we aim to optimize.

#### Reliance on fragmented collections of proprietary software

By embracing open source, we can leverage the talent of the entire insurance community to build better tools. The transparency in both implementation and design decisions enables teams to more effectively utilize the tools and influence development direction.

#### Bespoke processes 

There are considerable commonalities in actuarial workflows. By developing common tooling based on best practices instead of repeatedly reinventing the wheel, we can focus more on impactful problems.

#### Limited access to capabilities

Is it difficult for smaller carriers without significant R&D investments to procure the interdisciplinary knowledge necessary to develop and implement AI projects. It is also challenging for regulators, who are often resource constrained, to review and approve models based on newer technologies. By making this knowledge readily available, we encourage greater participation in the feedback and innovation cycle.

### Kasa AI

Out of the gate, Kasa AI will focus on the following types of projects:

- Conducting applied artificial intelligence **research** and author papers and blog posts.
- Developing open source **software** to enable adoption of new technologies in practice.
- Creating **educational** material to help teams transition to code-first and reproducible workflows.

To undertake these activities, we currently depend on time from volunteers, who are professionals and researchers from industry and academia. Members of the community form teams that serve as core contributors of each project and are responsible for their execution. An informal network of [advisors](https://kasa.ai/about/#people), who have specific technical expertise or community building experience, assist with everything from coordinating peer review to advocating for the initiative.

We intend to eventually cover all aspects of insurance that will be affected by AI, and are not limited to specific subfields of insurance. Our approach will have a practical slant, focusing on projects that can be implemented in real life in the near term. This also means we will be mindful of the regulatory environments that the consumers of our output operate in and structuring solutions accordingly.

We will open source all code and, to the extent possible, the data, so that others can validate our results and build upon them. In cases where data essential to the analyses cannot be shared due to, for example, privacy regulations, we will perform parallel experiments using simulated or augmented publicly available data. Because data access is critical in enabling research, some of our initial efforts will be focused on curating existing publicly available data and understanding required levels of privacy guarantees needed in building models to synthesize data.

We offer resources and opportunities to contribute regardless of where teams are in terms of technical capabilities. For example, we recognize that, for many, the first step may be moving beyond spreadsheets for data intensive tasks, and we aim to provide a support network to facilitate the transition.

### Looking Ahead

Many challenges await us. There is a skill gap in software and predictive modeling for many actuaries, which has been recognized and is being addressed by actuarial organizations around the world; we will support them in this effort as we shepherd the projects. Democratizing AI in insurance means, to an extent, leveling the playing field for players in the industry, but will allow insurance professionals to focus their efforts on solving more creative problems. We hope this movement will demonstrate that open science can result in higher returns on investment, which has been evident in other industries.

### Getting Involved

We invite practitioners, academics, and students interested in insurance to join us in this journey. As this is an interdisciplinary effort, neither software development or actuarial experience is a prerequisite. Look through the [quests.kasa.ai](https://quests.kasa.ai) for ongoing projects to participate in and propose new ones by opening a [GitHub issue](https://github.com/kasaai/quests/issues). You can also swing by our [Slack workspace](https://slack.kasa.ai) or sign up for our newsletter at [kasa.ai](https://kasa.ai).